-- Seed the remaining 331 official Chilean comunas (346 total minus the 15
-- already seeded) as status='excluded' — data only, no behavior change.
--
-- Why: matchRegionId (apps/curator/src/lib/locations.ts) only tags an
-- event's region_id when its freeform_location text matches a NAME already
-- present in this table — regardless of that region's status (loadAllRegions
-- in run.ts loads every region, not just 'active' ones, specifically for
-- this tagging purpose). Bright sources like arteinformado.com already
-- return real events from comunas we hadn't seeded yet (Las Condes,
-- Vitacura, El Bosque — found 2026-07-17) — those events were landing with
-- region_id=null (the "otro" bucket) purely because the comuna name didn't
-- exist as a row yet, not because we don't otherwise have real data for
-- them. Seeding every comuna's name fixes that tagging gap immediately.
--
-- status='excluded' is deliberate: getUnitsDueForRun filters
-- `.neq('status', 'excluded')`, so none of these 331 enter the active
-- per-unit Tavily search loop — this migration does NOT expand search
-- coverage or spend any Tavily/Anthropic budget, only whatever a comuna
-- ALREADY organically surfaces through Tavily/bright-source results (which
-- were being silently dropped into "otro" before). Turning any of these
-- into a real active search unit (search_frequency, population, etc.) is a
-- separate, deliberate decision — see the 346-comuna gradual-rollout
-- discussion in docs/region-discovery.md, not something this migration
-- decides on its own.
--
-- Source: Chile's official comuna count (346) cross-checked against a
-- structured dataset (github.com/juanbrujo/chile-regiones-comunas), not
-- typed from memory, to avoid subtly wrong/misspelled names silently
-- breaking future text matches. Two names double-checked as genuinely
-- real, not data-source errors: "Florida" (Biobío region — a real, distinct
-- comuna from Santiago's already-seeded "La Florida") and "O'Higgins"
-- (Aisén region — a real comuna, distinct from the O'Higgins REGION, a
-- different administrative level). "Cabo de Hornos" seeded under its
-- current official name only (source listed it as "Cabo de Hornos (Ex
-- Navarino)", its pre-2019 name — the historical annotation is dropped
-- since real sources will only ever say "Cabo de Hornos").
--
-- No ON CONFLICT clause: `name` has no unique constraint on this table, so
-- there's nothing to conflict on — a plain insert. Supabase tracks applied
-- migrations itself and won't re-run this file, so re-run safety isn't a
-- concern in normal flow.

insert into regions (name, country, language, status)
values
  ('Aisén', 'Chile', 'es', 'excluded'),
  ('Algarrobo', 'Chile', 'es', 'excluded'),
  ('Alhué', 'Chile', 'es', 'excluded'),
  ('Alto Biobío', 'Chile', 'es', 'excluded'),
  ('Alto Hospicio', 'Chile', 'es', 'excluded'),
  ('Alto del Carmen', 'Chile', 'es', 'excluded'),
  ('Ancud', 'Chile', 'es', 'excluded'),
  ('Andacollo', 'Chile', 'es', 'excluded'),
  ('Angol', 'Chile', 'es', 'excluded'),
  ('Antuco', 'Chile', 'es', 'excluded'),
  ('Antártica', 'Chile', 'es', 'excluded'),
  ('Arauco', 'Chile', 'es', 'excluded'),
  ('Buin', 'Chile', 'es', 'excluded'),
  ('Bulnes', 'Chile', 'es', 'excluded'),
  ('Cabildo', 'Chile', 'es', 'excluded'),
  ('Cabo de Hornos', 'Chile', 'es', 'excluded'),
  ('Cabrero', 'Chile', 'es', 'excluded'),
  ('Calama', 'Chile', 'es', 'excluded'),
  ('Calbuco', 'Chile', 'es', 'excluded'),
  ('Caldera', 'Chile', 'es', 'excluded'),
  ('Calera', 'Chile', 'es', 'excluded'),
  ('Calera de Tango', 'Chile', 'es', 'excluded'),
  ('Calle Larga', 'Chile', 'es', 'excluded'),
  ('Camarones', 'Chile', 'es', 'excluded'),
  ('Camiña', 'Chile', 'es', 'excluded'),
  ('Canela', 'Chile', 'es', 'excluded'),
  ('Carahue', 'Chile', 'es', 'excluded'),
  ('Cartagena', 'Chile', 'es', 'excluded'),
  ('Casablanca', 'Chile', 'es', 'excluded'),
  ('Castro', 'Chile', 'es', 'excluded'),
  ('Catemu', 'Chile', 'es', 'excluded'),
  ('Cauquenes', 'Chile', 'es', 'excluded'),
  ('Cañete', 'Chile', 'es', 'excluded'),
  ('Cerrillos', 'Chile', 'es', 'excluded'),
  ('Cerro Navia', 'Chile', 'es', 'excluded'),
  ('Chaitén', 'Chile', 'es', 'excluded'),
  ('Chanco', 'Chile', 'es', 'excluded'),
  ('Chañaral', 'Chile', 'es', 'excluded'),
  ('Chiguayante', 'Chile', 'es', 'excluded'),
  ('Chile Chico', 'Chile', 'es', 'excluded'),
  ('Chillán', 'Chile', 'es', 'excluded'),
  ('Chillán Viejo', 'Chile', 'es', 'excluded'),
  ('Chimbarongo', 'Chile', 'es', 'excluded'),
  ('Cholchol', 'Chile', 'es', 'excluded'),
  ('Chonchi', 'Chile', 'es', 'excluded'),
  ('Chépica', 'Chile', 'es', 'excluded'),
  ('Cisnes', 'Chile', 'es', 'excluded'),
  ('Cobquecura', 'Chile', 'es', 'excluded'),
  ('Cochamó', 'Chile', 'es', 'excluded'),
  ('Cochrane', 'Chile', 'es', 'excluded'),
  ('Codegua', 'Chile', 'es', 'excluded'),
  ('Coelemu', 'Chile', 'es', 'excluded'),
  ('Coihaique', 'Chile', 'es', 'excluded'),
  ('Coihueco', 'Chile', 'es', 'excluded'),
  ('Coinco', 'Chile', 'es', 'excluded'),
  ('Colbún', 'Chile', 'es', 'excluded'),
  ('Colchane', 'Chile', 'es', 'excluded'),
  ('Colina', 'Chile', 'es', 'excluded'),
  ('Collipulli', 'Chile', 'es', 'excluded'),
  ('Coltauco', 'Chile', 'es', 'excluded'),
  ('Combarbalá', 'Chile', 'es', 'excluded'),
  ('Conchalí', 'Chile', 'es', 'excluded'),
  ('Concón', 'Chile', 'es', 'excluded'),
  ('Constitución', 'Chile', 'es', 'excluded'),
  ('Contulmo', 'Chile', 'es', 'excluded'),
  ('Copiapó', 'Chile', 'es', 'excluded'),
  ('Coquimbo', 'Chile', 'es', 'excluded'),
  ('Coronel', 'Chile', 'es', 'excluded'),
  ('Corral', 'Chile', 'es', 'excluded'),
  ('Cunco', 'Chile', 'es', 'excluded'),
  ('Curacautín', 'Chile', 'es', 'excluded'),
  ('Curacaví', 'Chile', 'es', 'excluded'),
  ('Curaco de Vélez', 'Chile', 'es', 'excluded'),
  ('Curanilahue', 'Chile', 'es', 'excluded'),
  ('Curarrehue', 'Chile', 'es', 'excluded'),
  ('Curepto', 'Chile', 'es', 'excluded'),
  ('Curicó', 'Chile', 'es', 'excluded'),
  ('Dalcahue', 'Chile', 'es', 'excluded'),
  ('Diego de Almagro', 'Chile', 'es', 'excluded'),
  ('Doñihue', 'Chile', 'es', 'excluded'),
  ('El Bosque', 'Chile', 'es', 'excluded'),
  ('El Carmen', 'Chile', 'es', 'excluded'),
  ('El Monte', 'Chile', 'es', 'excluded'),
  ('El Quisco', 'Chile', 'es', 'excluded'),
  ('El Tabo', 'Chile', 'es', 'excluded'),
  ('Empedrado', 'Chile', 'es', 'excluded'),
  ('Ercilla', 'Chile', 'es', 'excluded'),
  ('Estación Central', 'Chile', 'es', 'excluded'),
  ('Florida', 'Chile', 'es', 'excluded'),
  ('Freire', 'Chile', 'es', 'excluded'),
  ('Freirina', 'Chile', 'es', 'excluded'),
  ('Fresia', 'Chile', 'es', 'excluded'),
  ('Futaleufú', 'Chile', 'es', 'excluded'),
  ('Futrono', 'Chile', 'es', 'excluded'),
  ('Galvarino', 'Chile', 'es', 'excluded'),
  ('General Lagos', 'Chile', 'es', 'excluded'),
  ('Gorbea', 'Chile', 'es', 'excluded'),
  ('Graneros', 'Chile', 'es', 'excluded'),
  ('Guaitecas', 'Chile', 'es', 'excluded'),
  ('Hijuelas', 'Chile', 'es', 'excluded'),
  ('Hualaihué', 'Chile', 'es', 'excluded'),
  ('Hualañé', 'Chile', 'es', 'excluded'),
  ('Hualpén', 'Chile', 'es', 'excluded'),
  ('Hualqui', 'Chile', 'es', 'excluded'),
  ('Huara', 'Chile', 'es', 'excluded'),
  ('Huasco', 'Chile', 'es', 'excluded'),
  ('Huechuraba', 'Chile', 'es', 'excluded'),
  ('Illapel', 'Chile', 'es', 'excluded'),
  ('Iquique', 'Chile', 'es', 'excluded'),
  ('Isla de Maipo', 'Chile', 'es', 'excluded'),
  ('Isla de Pascua', 'Chile', 'es', 'excluded'),
  ('Juan Fernández', 'Chile', 'es', 'excluded'),
  ('La Cisterna', 'Chile', 'es', 'excluded'),
  ('La Cruz', 'Chile', 'es', 'excluded'),
  ('La Estrella', 'Chile', 'es', 'excluded'),
  ('La Granja', 'Chile', 'es', 'excluded'),
  ('La Higuera', 'Chile', 'es', 'excluded'),
  ('La Ligua', 'Chile', 'es', 'excluded'),
  ('La Pintana', 'Chile', 'es', 'excluded'),
  ('La Serena', 'Chile', 'es', 'excluded'),
  ('La Unión', 'Chile', 'es', 'excluded'),
  ('Lago Ranco', 'Chile', 'es', 'excluded'),
  ('Lago Verde', 'Chile', 'es', 'excluded'),
  ('Laguna Blanca', 'Chile', 'es', 'excluded'),
  ('Laja', 'Chile', 'es', 'excluded'),
  ('Lampa', 'Chile', 'es', 'excluded'),
  ('Lanco', 'Chile', 'es', 'excluded'),
  ('Las Cabras', 'Chile', 'es', 'excluded'),
  ('Las Condes', 'Chile', 'es', 'excluded'),
  ('Lautaro', 'Chile', 'es', 'excluded'),
  ('Lebu', 'Chile', 'es', 'excluded'),
  ('Licantén', 'Chile', 'es', 'excluded'),
  ('Limache', 'Chile', 'es', 'excluded'),
  ('Linares', 'Chile', 'es', 'excluded'),
  ('Litueche', 'Chile', 'es', 'excluded'),
  ('Llaillay', 'Chile', 'es', 'excluded'),
  ('Llanquihue', 'Chile', 'es', 'excluded'),
  ('Lo Barnechea', 'Chile', 'es', 'excluded'),
  ('Lo Espejo', 'Chile', 'es', 'excluded'),
  ('Lo Prado', 'Chile', 'es', 'excluded'),
  ('Lolol', 'Chile', 'es', 'excluded'),
  ('Loncoche', 'Chile', 'es', 'excluded'),
  ('Longaví', 'Chile', 'es', 'excluded'),
  ('Lonquimay', 'Chile', 'es', 'excluded'),
  ('Los Andes', 'Chile', 'es', 'excluded'),
  ('Los Lagos', 'Chile', 'es', 'excluded'),
  ('Los Muermos', 'Chile', 'es', 'excluded'),
  ('Los Sauces', 'Chile', 'es', 'excluded'),
  ('Los Vilos', 'Chile', 'es', 'excluded'),
  ('Los Álamos', 'Chile', 'es', 'excluded'),
  ('Los Ángeles', 'Chile', 'es', 'excluded'),
  ('Lota', 'Chile', 'es', 'excluded'),
  ('Lumaco', 'Chile', 'es', 'excluded'),
  ('Machalí', 'Chile', 'es', 'excluded'),
  ('Macul', 'Chile', 'es', 'excluded'),
  ('Malloa', 'Chile', 'es', 'excluded'),
  ('Marchihue', 'Chile', 'es', 'excluded'),
  ('Mariquina', 'Chile', 'es', 'excluded'),
  ('María Elena', 'Chile', 'es', 'excluded'),
  ('María Pinto', 'Chile', 'es', 'excluded'),
  ('Maule', 'Chile', 'es', 'excluded'),
  ('Maullín', 'Chile', 'es', 'excluded'),
  ('Mejillones', 'Chile', 'es', 'excluded'),
  ('Melipeuco', 'Chile', 'es', 'excluded'),
  ('Melipilla', 'Chile', 'es', 'excluded'),
  ('Molina', 'Chile', 'es', 'excluded'),
  ('Monte Patria', 'Chile', 'es', 'excluded'),
  ('Mostazal', 'Chile', 'es', 'excluded'),
  ('Mulchén', 'Chile', 'es', 'excluded'),
  ('Máfil', 'Chile', 'es', 'excluded'),
  ('Nacimiento', 'Chile', 'es', 'excluded'),
  ('Nancagua', 'Chile', 'es', 'excluded'),
  ('Natales', 'Chile', 'es', 'excluded'),
  ('Navidad', 'Chile', 'es', 'excluded'),
  ('Negrete', 'Chile', 'es', 'excluded'),
  ('Ninhue', 'Chile', 'es', 'excluded'),
  ('Nogales', 'Chile', 'es', 'excluded'),
  ('Nueva Imperial', 'Chile', 'es', 'excluded'),
  ('O''Higgins', 'Chile', 'es', 'excluded'),
  ('Olivar', 'Chile', 'es', 'excluded'),
  ('Ollagüe', 'Chile', 'es', 'excluded'),
  ('Olmué', 'Chile', 'es', 'excluded'),
  ('Osorno', 'Chile', 'es', 'excluded'),
  ('Ovalle', 'Chile', 'es', 'excluded'),
  ('Padre Hurtado', 'Chile', 'es', 'excluded'),
  ('Padre las Casas', 'Chile', 'es', 'excluded'),
  ('Paiguano', 'Chile', 'es', 'excluded'),
  ('Paillaco', 'Chile', 'es', 'excluded'),
  ('Paine', 'Chile', 'es', 'excluded'),
  ('Palena', 'Chile', 'es', 'excluded'),
  ('Palmilla', 'Chile', 'es', 'excluded'),
  ('Panguipulli', 'Chile', 'es', 'excluded'),
  ('Panquehue', 'Chile', 'es', 'excluded'),
  ('Papudo', 'Chile', 'es', 'excluded'),
  ('Paredones', 'Chile', 'es', 'excluded'),
  ('Parral', 'Chile', 'es', 'excluded'),
  ('Pedro Aguirre Cerda', 'Chile', 'es', 'excluded'),
  ('Pelarco', 'Chile', 'es', 'excluded'),
  ('Pelluhue', 'Chile', 'es', 'excluded'),
  ('Pemuco', 'Chile', 'es', 'excluded'),
  ('Pencahue', 'Chile', 'es', 'excluded'),
  ('Penco', 'Chile', 'es', 'excluded'),
  ('Peralillo', 'Chile', 'es', 'excluded'),
  ('Perquenco', 'Chile', 'es', 'excluded'),
  ('Petorca', 'Chile', 'es', 'excluded'),
  ('Peumo', 'Chile', 'es', 'excluded'),
  ('Peñaflor', 'Chile', 'es', 'excluded'),
  ('Peñalolén', 'Chile', 'es', 'excluded'),
  ('Pica', 'Chile', 'es', 'excluded'),
  ('Pichidegua', 'Chile', 'es', 'excluded'),
  ('Pichilemu', 'Chile', 'es', 'excluded'),
  ('Pinto', 'Chile', 'es', 'excluded'),
  ('Pirque', 'Chile', 'es', 'excluded'),
  ('Pitrufquén', 'Chile', 'es', 'excluded'),
  ('Placilla', 'Chile', 'es', 'excluded'),
  ('Portezuelo', 'Chile', 'es', 'excluded'),
  ('Porvenir', 'Chile', 'es', 'excluded'),
  ('Pozo Almonte', 'Chile', 'es', 'excluded'),
  ('Primavera', 'Chile', 'es', 'excluded'),
  ('Puchuncaví', 'Chile', 'es', 'excluded'),
  ('Pucón', 'Chile', 'es', 'excluded'),
  ('Pudahuel', 'Chile', 'es', 'excluded'),
  ('Puerto Montt', 'Chile', 'es', 'excluded'),
  ('Puerto Octay', 'Chile', 'es', 'excluded'),
  ('Puerto Varas', 'Chile', 'es', 'excluded'),
  ('Pumanque', 'Chile', 'es', 'excluded'),
  ('Punitaqui', 'Chile', 'es', 'excluded'),
  ('Punta Arenas', 'Chile', 'es', 'excluded'),
  ('Puqueldón', 'Chile', 'es', 'excluded'),
  ('Purranque', 'Chile', 'es', 'excluded'),
  ('Purén', 'Chile', 'es', 'excluded'),
  ('Putaendo', 'Chile', 'es', 'excluded'),
  ('Putre', 'Chile', 'es', 'excluded'),
  ('Puyehue', 'Chile', 'es', 'excluded'),
  ('Queilén', 'Chile', 'es', 'excluded'),
  ('Quellón', 'Chile', 'es', 'excluded'),
  ('Quemchi', 'Chile', 'es', 'excluded'),
  ('Quilaco', 'Chile', 'es', 'excluded'),
  ('Quilicura', 'Chile', 'es', 'excluded'),
  ('Quilleco', 'Chile', 'es', 'excluded'),
  ('Quillota', 'Chile', 'es', 'excluded'),
  ('Quillón', 'Chile', 'es', 'excluded'),
  ('Quilpué', 'Chile', 'es', 'excluded'),
  ('Quinchao', 'Chile', 'es', 'excluded'),
  ('Quinta Normal', 'Chile', 'es', 'excluded'),
  ('Quinta de Tilcoco', 'Chile', 'es', 'excluded'),
  ('Quintero', 'Chile', 'es', 'excluded'),
  ('Quirihue', 'Chile', 'es', 'excluded'),
  ('Rancagua', 'Chile', 'es', 'excluded'),
  ('Rauco', 'Chile', 'es', 'excluded'),
  ('Renaico', 'Chile', 'es', 'excluded'),
  ('Rengo', 'Chile', 'es', 'excluded'),
  ('Requínoa', 'Chile', 'es', 'excluded'),
  ('Retiro', 'Chile', 'es', 'excluded'),
  ('Rinconada', 'Chile', 'es', 'excluded'),
  ('Romeral', 'Chile', 'es', 'excluded'),
  ('Ránquil', 'Chile', 'es', 'excluded'),
  ('Río Bueno', 'Chile', 'es', 'excluded'),
  ('Río Claro', 'Chile', 'es', 'excluded'),
  ('Río Hurtado', 'Chile', 'es', 'excluded'),
  ('Río Ibáñez', 'Chile', 'es', 'excluded'),
  ('Río Negro', 'Chile', 'es', 'excluded'),
  ('Río Verde', 'Chile', 'es', 'excluded'),
  ('Saavedra', 'Chile', 'es', 'excluded'),
  ('Sagrada Familia', 'Chile', 'es', 'excluded'),
  ('Salamanca', 'Chile', 'es', 'excluded'),
  ('San Antonio', 'Chile', 'es', 'excluded'),
  ('San Bernardo', 'Chile', 'es', 'excluded'),
  ('San Carlos', 'Chile', 'es', 'excluded'),
  ('San Clemente', 'Chile', 'es', 'excluded'),
  ('San Esteban', 'Chile', 'es', 'excluded'),
  ('San Fabián', 'Chile', 'es', 'excluded'),
  ('San Felipe', 'Chile', 'es', 'excluded'),
  ('San Fernando', 'Chile', 'es', 'excluded'),
  ('San Gregorio', 'Chile', 'es', 'excluded'),
  ('San Ignacio', 'Chile', 'es', 'excluded'),
  ('San Javier', 'Chile', 'es', 'excluded'),
  ('San Joaquín', 'Chile', 'es', 'excluded'),
  ('San José de Maipo', 'Chile', 'es', 'excluded'),
  ('San Juan de la Costa', 'Chile', 'es', 'excluded'),
  ('San Miguel', 'Chile', 'es', 'excluded'),
  ('San Nicolás', 'Chile', 'es', 'excluded'),
  ('San Pablo', 'Chile', 'es', 'excluded'),
  ('San Pedro', 'Chile', 'es', 'excluded'),
  ('San Pedro de Atacama', 'Chile', 'es', 'excluded'),
  ('San Pedro de la Paz', 'Chile', 'es', 'excluded'),
  ('San Rafael', 'Chile', 'es', 'excluded'),
  ('San Ramón', 'Chile', 'es', 'excluded'),
  ('San Rosendo', 'Chile', 'es', 'excluded'),
  ('San Vicente', 'Chile', 'es', 'excluded'),
  ('Santa Bárbara', 'Chile', 'es', 'excluded'),
  ('Santa Cruz', 'Chile', 'es', 'excluded'),
  ('Santa Juana', 'Chile', 'es', 'excluded'),
  ('Santa María', 'Chile', 'es', 'excluded'),
  ('Santo Domingo', 'Chile', 'es', 'excluded'),
  ('Sierra Gorda', 'Chile', 'es', 'excluded'),
  ('Talagante', 'Chile', 'es', 'excluded'),
  ('Talca', 'Chile', 'es', 'excluded'),
  ('Talcahuano', 'Chile', 'es', 'excluded'),
  ('Taltal', 'Chile', 'es', 'excluded'),
  ('Temuco', 'Chile', 'es', 'excluded'),
  ('Teno', 'Chile', 'es', 'excluded'),
  ('Teodoro Schmidt', 'Chile', 'es', 'excluded'),
  ('Tierra Amarilla', 'Chile', 'es', 'excluded'),
  ('Tiltil', 'Chile', 'es', 'excluded'),
  ('Timaukel', 'Chile', 'es', 'excluded'),
  ('Tirúa', 'Chile', 'es', 'excluded'),
  ('Tocopilla', 'Chile', 'es', 'excluded'),
  ('Toltén', 'Chile', 'es', 'excluded'),
  ('Tomé', 'Chile', 'es', 'excluded'),
  ('Torres del Paine', 'Chile', 'es', 'excluded'),
  ('Tortel', 'Chile', 'es', 'excluded'),
  ('Traiguén', 'Chile', 'es', 'excluded'),
  ('Treguaco', 'Chile', 'es', 'excluded'),
  ('Tucapel', 'Chile', 'es', 'excluded'),
  ('Valdivia', 'Chile', 'es', 'excluded'),
  ('Vallenar', 'Chile', 'es', 'excluded'),
  ('Vichuquén', 'Chile', 'es', 'excluded'),
  ('Victoria', 'Chile', 'es', 'excluded'),
  ('Vicuña', 'Chile', 'es', 'excluded'),
  ('Vilcún', 'Chile', 'es', 'excluded'),
  ('Villa Alegre', 'Chile', 'es', 'excluded'),
  ('Villa Alemana', 'Chile', 'es', 'excluded'),
  ('Villarrica', 'Chile', 'es', 'excluded'),
  ('Vitacura', 'Chile', 'es', 'excluded'),
  ('Viña del Mar', 'Chile', 'es', 'excluded'),
  ('Yerbas Buenas', 'Chile', 'es', 'excluded'),
  ('Yumbel', 'Chile', 'es', 'excluded'),
  ('Yungay', 'Chile', 'es', 'excluded'),
  ('Zapallar', 'Chile', 'es', 'excluded'),
  ('Ñiquén', 'Chile', 'es', 'excluded');
