-- City picker redesign needs Chile's real administrative macro-regions
-- (I-XVI, Región Metropolitana) with a geographic north-to-south sort
-- order — neither exists anywhere today. `regions` (despite its name,
-- one row per COMUNA, not macro-region) has no such column, and no
-- comuna->macro-region mapping table exists in this schema or in
-- application code.
--
-- Both new columns are nullable BY DESIGN, not left incomplete: this is
-- the scalability hook for a future country. A new country's comunas can
-- be seeded with just name/country and no macro-region data yet — the
-- frontend groups anything with admin_region_name IS NULL into a "sin
-- región" fallback bucket instead of crashing or silently dropping it
-- (see apps/web/src/lib/cities.ts's groupCitiesByRegion).
--
-- admin_region_order is a plain geographic rank (1=northernmost), NOT the
-- Chilean Roman-numeral region number — those two diverge (XV Arica y
-- Parinacota and XVI Ñuble are the newest regions, numbered out of
-- geographic sequence when created; Arica y Parinacota is genuinely the
-- northernmost region despite being "XV", and Ñuble sits between VII
-- Maule and VIII Biobío despite being "XVI").
--
-- Source: data/zefrox-slugs-updated.json from the same
-- github.com/juanbrujo/chile-regiones-comunas dataset already cited in
-- 20260717000000_seed_remaining_chile_comunas_excluded.sql as the source
-- of the 346 comuna names — its 16-region array is already in correct
-- geographic north-to-south order, used directly as admin_region_order
-- below. Cross-checked against all 346 live comuna names in this table:
-- 342 matched directly; "Cabo de Hornos (Ex Navarino)" matched this
-- table's "Cabo de Hornos" (same historical-name situation already noted
-- in the seed migration); El Monte, Isla de Maipo, Padre Hurtado, and
-- Peñaflor (all real Talagante-province comunas, Región Metropolitana)
-- were missing from that dataset entirely and are assigned directly here.

alter table regions add column admin_region_name text;
alter table regions add column admin_region_order integer;

update regions r set
  admin_region_name = v.admin_region_name,
  admin_region_order = v.admin_region_order
from (values
  ('Aisén', 'Región Aisén del Gral. Carlos Ibáñez del Campo', 14),
  ('Algarrobo', 'Valparaíso', 6),
  ('Alhué', 'Región Metropolitana de Santiago', 16),
  ('Alto Biobío', 'Región del Biobío', 10),
  ('Alto Hospicio', 'Tarapacá', 2),
  ('Alto del Carmen', 'Atacama', 4),
  ('Ancud', 'Región de Los Lagos', 13),
  ('Andacollo', 'Coquimbo', 5),
  ('Angol', 'Región de la Araucanía', 11),
  ('Antofagasta', 'Antofagasta', 3),
  ('Antuco', 'Región del Biobío', 10),
  ('Antártica', 'Región de Magallanes y de la Antártica Chilena', 15),
  ('Arauco', 'Región del Biobío', 10),
  ('Arica', 'Arica y Parinacota', 1),
  ('Buin', 'Región Metropolitana de Santiago', 16),
  ('Bulnes', 'Región de Ñuble', 9),
  ('Cabildo', 'Valparaíso', 6),
  ('Cabo de Hornos', 'Región de Magallanes y de la Antártica Chilena', 15),
  ('Cabrero', 'Región del Biobío', 10),
  ('Calama', 'Antofagasta', 3),
  ('Calbuco', 'Región de Los Lagos', 13),
  ('Caldera', 'Atacama', 4),
  ('Calera', 'Valparaíso', 6),
  ('Calera de Tango', 'Región Metropolitana de Santiago', 16),
  ('Calle Larga', 'Valparaíso', 6),
  ('Camarones', 'Arica y Parinacota', 1),
  ('Camiña', 'Tarapacá', 2),
  ('Canela', 'Coquimbo', 5),
  ('Carahue', 'Región de la Araucanía', 11),
  ('Cartagena', 'Valparaíso', 6),
  ('Casablanca', 'Valparaíso', 6),
  ('Castro', 'Región de Los Lagos', 13),
  ('Catemu', 'Valparaíso', 6),
  ('Cauquenes', 'Región del Maule', 8),
  ('Cañete', 'Región del Biobío', 10),
  ('Cerrillos', 'Región Metropolitana de Santiago', 16),
  ('Cerro Navia', 'Región Metropolitana de Santiago', 16),
  ('Chaitén', 'Región de Los Lagos', 13),
  ('Chanco', 'Región del Maule', 8),
  ('Chañaral', 'Atacama', 4),
  ('Chiguayante', 'Región del Biobío', 10),
  ('Chile Chico', 'Región Aisén del Gral. Carlos Ibáñez del Campo', 14),
  ('Chillán', 'Región de Ñuble', 9),
  ('Chillán Viejo', 'Región de Ñuble', 9),
  ('Chimbarongo', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('Cholchol', 'Región de la Araucanía', 11),
  ('Chonchi', 'Región de Los Lagos', 13),
  ('Chépica', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('Cisnes', 'Región Aisén del Gral. Carlos Ibáñez del Campo', 14),
  ('Cobquecura', 'Región de Ñuble', 9),
  ('Cochamó', 'Región de Los Lagos', 13),
  ('Cochrane', 'Región Aisén del Gral. Carlos Ibáñez del Campo', 14),
  ('Codegua', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('Coelemu', 'Región de Ñuble', 9),
  ('Coihaique', 'Región Aisén del Gral. Carlos Ibáñez del Campo', 14),
  ('Coihueco', 'Región de Ñuble', 9),
  ('Coinco', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('Colbún', 'Región del Maule', 8),
  ('Colchane', 'Tarapacá', 2),
  ('Colina', 'Región Metropolitana de Santiago', 16),
  ('Collipulli', 'Región de la Araucanía', 11),
  ('Coltauco', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('Combarbalá', 'Coquimbo', 5),
  ('Concepción', 'Región del Biobío', 10),
  ('Conchalí', 'Región Metropolitana de Santiago', 16),
  ('Concón', 'Valparaíso', 6),
  ('Constitución', 'Región del Maule', 8),
  ('Contulmo', 'Región del Biobío', 10),
  ('Copiapó', 'Atacama', 4),
  ('Coquimbo', 'Coquimbo', 5),
  ('Coronel', 'Región del Biobío', 10),
  ('Corral', 'Región de Los Ríos', 12),
  ('Cunco', 'Región de la Araucanía', 11),
  ('Curacautín', 'Región de la Araucanía', 11),
  ('Curacaví', 'Región Metropolitana de Santiago', 16),
  ('Curaco de Vélez', 'Región de Los Lagos', 13),
  ('Curanilahue', 'Región del Biobío', 10),
  ('Curarrehue', 'Región de la Araucanía', 11),
  ('Curepto', 'Región del Maule', 8),
  ('Curicó', 'Región del Maule', 8),
  ('Dalcahue', 'Región de Los Lagos', 13),
  ('Diego de Almagro', 'Atacama', 4),
  ('Doñihue', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('El Bosque', 'Región Metropolitana de Santiago', 16),
  ('El Carmen', 'Región de Ñuble', 9),
  ('El Monte', 'Región Metropolitana de Santiago', 16),
  ('El Quisco', 'Valparaíso', 6),
  ('El Tabo', 'Valparaíso', 6),
  ('Empedrado', 'Región del Maule', 8),
  ('Ercilla', 'Región de la Araucanía', 11),
  ('Estación Central', 'Región Metropolitana de Santiago', 16),
  ('Florida', 'Región del Biobío', 10),
  ('Freire', 'Región de la Araucanía', 11),
  ('Freirina', 'Atacama', 4),
  ('Fresia', 'Región de Los Lagos', 13),
  ('Frutillar', 'Región de Los Lagos', 13),
  ('Futaleufú', 'Región de Los Lagos', 13),
  ('Futrono', 'Región de Los Ríos', 12),
  ('Galvarino', 'Región de la Araucanía', 11),
  ('General Lagos', 'Arica y Parinacota', 1),
  ('Gorbea', 'Región de la Araucanía', 11),
  ('Graneros', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('Guaitecas', 'Región Aisén del Gral. Carlos Ibáñez del Campo', 14),
  ('Hijuelas', 'Valparaíso', 6),
  ('Hualaihué', 'Región de Los Lagos', 13),
  ('Hualañé', 'Región del Maule', 8),
  ('Hualpén', 'Región del Biobío', 10),
  ('Hualqui', 'Región del Biobío', 10),
  ('Huara', 'Tarapacá', 2),
  ('Huasco', 'Atacama', 4),
  ('Huechuraba', 'Región Metropolitana de Santiago', 16),
  ('Illapel', 'Coquimbo', 5),
  ('Independencia', 'Región Metropolitana de Santiago', 16),
  ('Iquique', 'Tarapacá', 2),
  ('Isla de Maipo', 'Región Metropolitana de Santiago', 16),
  ('Isla de Pascua', 'Valparaíso', 6),
  ('Juan Fernández', 'Valparaíso', 6),
  ('La Cisterna', 'Región Metropolitana de Santiago', 16),
  ('La Cruz', 'Valparaíso', 6),
  ('La Estrella', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('La Florida', 'Región Metropolitana de Santiago', 16),
  ('La Granja', 'Región Metropolitana de Santiago', 16),
  ('La Higuera', 'Coquimbo', 5),
  ('La Ligua', 'Valparaíso', 6),
  ('La Pintana', 'Región Metropolitana de Santiago', 16),
  ('La Reina', 'Región Metropolitana de Santiago', 16),
  ('La Serena', 'Coquimbo', 5),
  ('La Unión', 'Región de Los Ríos', 12),
  ('Lago Ranco', 'Región de Los Ríos', 12),
  ('Lago Verde', 'Región Aisén del Gral. Carlos Ibáñez del Campo', 14),
  ('Laguna Blanca', 'Región de Magallanes y de la Antártica Chilena', 15),
  ('Laja', 'Región del Biobío', 10),
  ('Lampa', 'Región Metropolitana de Santiago', 16),
  ('Lanco', 'Región de Los Ríos', 12),
  ('Las Cabras', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('Las Condes', 'Región Metropolitana de Santiago', 16),
  ('Lautaro', 'Región de la Araucanía', 11),
  ('Lebu', 'Región del Biobío', 10),
  ('Licantén', 'Región del Maule', 8),
  ('Limache', 'Valparaíso', 6),
  ('Linares', 'Región del Maule', 8),
  ('Litueche', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('Llaillay', 'Valparaíso', 6),
  ('Llanquihue', 'Región de Los Lagos', 13),
  ('Lo Barnechea', 'Región Metropolitana de Santiago', 16),
  ('Lo Espejo', 'Región Metropolitana de Santiago', 16),
  ('Lo Prado', 'Región Metropolitana de Santiago', 16),
  ('Lolol', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('Loncoche', 'Región de la Araucanía', 11),
  ('Longaví', 'Región del Maule', 8),
  ('Lonquimay', 'Región de la Araucanía', 11),
  ('Los Andes', 'Valparaíso', 6),
  ('Los Lagos', 'Región de Los Ríos', 12),
  ('Los Muermos', 'Región de Los Lagos', 13),
  ('Los Sauces', 'Región de la Araucanía', 11),
  ('Los Vilos', 'Coquimbo', 5),
  ('Los Álamos', 'Región del Biobío', 10),
  ('Los Ángeles', 'Región del Biobío', 10),
  ('Lota', 'Región del Biobío', 10),
  ('Lumaco', 'Región de la Araucanía', 11),
  ('Machalí', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('Macul', 'Región Metropolitana de Santiago', 16),
  ('Maipú', 'Región Metropolitana de Santiago', 16),
  ('Malloa', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('Marchihue', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('Mariquina', 'Región de Los Ríos', 12),
  ('María Elena', 'Antofagasta', 3),
  ('María Pinto', 'Región Metropolitana de Santiago', 16),
  ('Maule', 'Región del Maule', 8),
  ('Maullín', 'Región de Los Lagos', 13),
  ('Mejillones', 'Antofagasta', 3),
  ('Melipeuco', 'Región de la Araucanía', 11),
  ('Melipilla', 'Región Metropolitana de Santiago', 16),
  ('Molina', 'Región del Maule', 8),
  ('Monte Patria', 'Coquimbo', 5),
  ('Mostazal', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('Mulchén', 'Región del Biobío', 10),
  ('Máfil', 'Región de Los Ríos', 12),
  ('Nacimiento', 'Región del Biobío', 10),
  ('Nancagua', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('Natales', 'Región de Magallanes y de la Antártica Chilena', 15),
  ('Navidad', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('Negrete', 'Región del Biobío', 10),
  ('Ninhue', 'Región de Ñuble', 9),
  ('Nogales', 'Valparaíso', 6),
  ('Nueva Imperial', 'Región de la Araucanía', 11),
  ('O''Higgins', 'Región Aisén del Gral. Carlos Ibáñez del Campo', 14),
  ('Olivar', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('Ollagüe', 'Antofagasta', 3),
  ('Olmué', 'Valparaíso', 6),
  ('Osorno', 'Región de Los Lagos', 13),
  ('Ovalle', 'Coquimbo', 5),
  ('Padre Hurtado', 'Región Metropolitana de Santiago', 16),
  ('Padre las Casas', 'Región de la Araucanía', 11),
  ('Paiguano', 'Coquimbo', 5),
  ('Paillaco', 'Región de Los Ríos', 12),
  ('Paine', 'Región Metropolitana de Santiago', 16),
  ('Palena', 'Región de Los Lagos', 13),
  ('Palmilla', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('Panguipulli', 'Región de Los Ríos', 12),
  ('Panquehue', 'Valparaíso', 6),
  ('Papudo', 'Valparaíso', 6),
  ('Paredones', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('Parral', 'Región del Maule', 8),
  ('Pedro Aguirre Cerda', 'Región Metropolitana de Santiago', 16),
  ('Pelarco', 'Región del Maule', 8),
  ('Pelluhue', 'Región del Maule', 8),
  ('Pemuco', 'Región de Ñuble', 9),
  ('Pencahue', 'Región del Maule', 8),
  ('Penco', 'Región del Biobío', 10),
  ('Peralillo', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('Perquenco', 'Región de la Araucanía', 11),
  ('Petorca', 'Valparaíso', 6),
  ('Peumo', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('Peñaflor', 'Región Metropolitana de Santiago', 16),
  ('Peñalolén', 'Región Metropolitana de Santiago', 16),
  ('Pica', 'Tarapacá', 2),
  ('Pichidegua', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('Pichilemu', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('Pinto', 'Región de Ñuble', 9),
  ('Pirque', 'Región Metropolitana de Santiago', 16),
  ('Pitrufquén', 'Región de la Araucanía', 11),
  ('Placilla', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('Portezuelo', 'Región de Ñuble', 9),
  ('Porvenir', 'Región de Magallanes y de la Antártica Chilena', 15),
  ('Pozo Almonte', 'Tarapacá', 2),
  ('Primavera', 'Región de Magallanes y de la Antártica Chilena', 15),
  ('Providencia', 'Región Metropolitana de Santiago', 16),
  ('Puchuncaví', 'Valparaíso', 6),
  ('Pucón', 'Región de la Araucanía', 11),
  ('Pudahuel', 'Región Metropolitana de Santiago', 16),
  ('Puente Alto', 'Región Metropolitana de Santiago', 16),
  ('Puerto Montt', 'Región de Los Lagos', 13),
  ('Puerto Octay', 'Región de Los Lagos', 13),
  ('Puerto Varas', 'Región de Los Lagos', 13),
  ('Pumanque', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('Punitaqui', 'Coquimbo', 5),
  ('Punta Arenas', 'Región de Magallanes y de la Antártica Chilena', 15),
  ('Puqueldón', 'Región de Los Lagos', 13),
  ('Purranque', 'Región de Los Lagos', 13),
  ('Purén', 'Región de la Araucanía', 11),
  ('Putaendo', 'Valparaíso', 6),
  ('Putre', 'Arica y Parinacota', 1),
  ('Puyehue', 'Región de Los Lagos', 13),
  ('Queilén', 'Región de Los Lagos', 13),
  ('Quellón', 'Región de Los Lagos', 13),
  ('Quemchi', 'Región de Los Lagos', 13),
  ('Quilaco', 'Región del Biobío', 10),
  ('Quilicura', 'Región Metropolitana de Santiago', 16),
  ('Quilleco', 'Región del Biobío', 10),
  ('Quillota', 'Valparaíso', 6),
  ('Quillón', 'Región de Ñuble', 9),
  ('Quilpué', 'Valparaíso', 6),
  ('Quinchao', 'Región de Los Lagos', 13),
  ('Quinta Normal', 'Región Metropolitana de Santiago', 16),
  ('Quinta de Tilcoco', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('Quintero', 'Valparaíso', 6),
  ('Quirihue', 'Región de Ñuble', 9),
  ('Rancagua', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('Rauco', 'Región del Maule', 8),
  ('Recoleta', 'Región Metropolitana de Santiago', 16),
  ('Renaico', 'Región de la Araucanía', 11),
  ('Renca', 'Región Metropolitana de Santiago', 16),
  ('Rengo', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('Requínoa', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('Retiro', 'Región del Maule', 8),
  ('Rinconada', 'Valparaíso', 6),
  ('Romeral', 'Región del Maule', 8),
  ('Ránquil', 'Región de Ñuble', 9),
  ('Río Bueno', 'Región de Los Ríos', 12),
  ('Río Claro', 'Región del Maule', 8),
  ('Río Hurtado', 'Coquimbo', 5),
  ('Río Ibáñez', 'Región Aisén del Gral. Carlos Ibáñez del Campo', 14),
  ('Río Negro', 'Región de Los Lagos', 13),
  ('Río Verde', 'Región de Magallanes y de la Antártica Chilena', 15),
  ('Saavedra', 'Región de la Araucanía', 11),
  ('Sagrada Familia', 'Región del Maule', 8),
  ('Salamanca', 'Coquimbo', 5),
  ('San Antonio', 'Valparaíso', 6),
  ('San Bernardo', 'Región Metropolitana de Santiago', 16),
  ('San Carlos', 'Región de Ñuble', 9),
  ('San Clemente', 'Región del Maule', 8),
  ('San Esteban', 'Valparaíso', 6),
  ('San Fabián', 'Región de Ñuble', 9),
  ('San Felipe', 'Valparaíso', 6),
  ('San Fernando', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('San Gregorio', 'Región de Magallanes y de la Antártica Chilena', 15),
  ('San Ignacio', 'Región de Ñuble', 9),
  ('San Javier', 'Región del Maule', 8),
  ('San Joaquín', 'Región Metropolitana de Santiago', 16),
  ('San José de Maipo', 'Región Metropolitana de Santiago', 16),
  ('San Juan de la Costa', 'Región de Los Lagos', 13),
  ('San Miguel', 'Región Metropolitana de Santiago', 16),
  ('San Nicolás', 'Región de Ñuble', 9),
  ('San Pablo', 'Región de Los Lagos', 13),
  ('San Pedro', 'Región Metropolitana de Santiago', 16),
  ('San Pedro de Atacama', 'Antofagasta', 3),
  ('San Pedro de la Paz', 'Región del Biobío', 10),
  ('San Rafael', 'Región del Maule', 8),
  ('San Ramón', 'Región Metropolitana de Santiago', 16),
  ('San Rosendo', 'Región del Biobío', 10),
  ('San Vicente', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('Santa Bárbara', 'Región del Biobío', 10),
  ('Santa Cruz', 'Región del Libertador Gral. Bernardo O''Higgins', 7),
  ('Santa Juana', 'Región del Biobío', 10),
  ('Santa María', 'Valparaíso', 6),
  ('Santiago', 'Región Metropolitana de Santiago', 16),
  ('Santo Domingo', 'Valparaíso', 6),
  ('Sierra Gorda', 'Antofagasta', 3),
  ('Talagante', 'Región Metropolitana de Santiago', 16),
  ('Talca', 'Región del Maule', 8),
  ('Talcahuano', 'Región del Biobío', 10),
  ('Taltal', 'Antofagasta', 3),
  ('Temuco', 'Región de la Araucanía', 11),
  ('Teno', 'Región del Maule', 8),
  ('Teodoro Schmidt', 'Región de la Araucanía', 11),
  ('Tierra Amarilla', 'Atacama', 4),
  ('Tiltil', 'Región Metropolitana de Santiago', 16),
  ('Timaukel', 'Región de Magallanes y de la Antártica Chilena', 15),
  ('Tirúa', 'Región del Biobío', 10),
  ('Tocopilla', 'Antofagasta', 3),
  ('Toltén', 'Región de la Araucanía', 11),
  ('Tomé', 'Región del Biobío', 10),
  ('Torres del Paine', 'Región de Magallanes y de la Antártica Chilena', 15),
  ('Tortel', 'Región Aisén del Gral. Carlos Ibáñez del Campo', 14),
  ('Traiguén', 'Región de la Araucanía', 11),
  ('Treguaco', 'Región de Ñuble', 9),
  ('Tucapel', 'Región del Biobío', 10),
  ('Valdivia', 'Región de Los Ríos', 12),
  ('Vallenar', 'Atacama', 4),
  ('Valparaíso', 'Valparaíso', 6),
  ('Vichuquén', 'Región del Maule', 8),
  ('Victoria', 'Región de la Araucanía', 11),
  ('Vicuña', 'Coquimbo', 5),
  ('Vilcún', 'Región de la Araucanía', 11),
  ('Villa Alegre', 'Región del Maule', 8),
  ('Villa Alemana', 'Valparaíso', 6),
  ('Villarrica', 'Región de la Araucanía', 11),
  ('Vitacura', 'Región Metropolitana de Santiago', 16),
  ('Viña del Mar', 'Valparaíso', 6),
  ('Yerbas Buenas', 'Región del Maule', 8),
  ('Yumbel', 'Región del Biobío', 10),
  ('Yungay', 'Región de Ñuble', 9),
  ('Zapallar', 'Valparaíso', 6),
  ('Ñiquén', 'Región de Ñuble', 9),
  ('Ñuñoa', 'Región Metropolitana de Santiago', 16)
) as v(name, admin_region_name, admin_region_order)
where r.name = v.name;
