-- Follow-up to 20260717030000_add_admin_region_to_regions.sql: two fixes,
-- both surfaced by reviewing the approved city-picker mockup against what
-- was actually shipped.
--
-- 1) admin_region_order for Región Metropolitana de Santiago was wrong.
--    The source dataset's region array listed RM LAST (position 16) —
--    that's a data-entry artifact of the source, not real geography.
--    Santiago sits inland at roughly Valparaíso's latitude, north of
--    O'Higgins — RM's correct geographic slot is position 7, between V
--    Valparaíso and VI O'Higgins. Every región from O'Higgins through
--    Magallanes shifts down by one to make room. This was inherited
--    without independently checking against real geography — fixed here
--    by recomputing admin_region_order for all 346 rows against a
--    hand-verified 16-región geographic sequence (see the mockup: XV, I,
--    II, III, IV, V, RM, VI, VII, XVI, VIII, IX, XIV, X, XI, XII).
--
-- 2) admin_region_numeral (new column): the mockup shows each región's
--    official Chilean numbering as a pill ("II", "V", "RM", "XV"...) —
--    distinct from admin_region_order, which is a pure geographic rank,
--    not Chile's official (non-geographic) numbering. Sourced from the
--    same data/zefrox-slugs-updated.json dataset's romanNumber field
--    (github.com/juanbrujo/chile-regiones-comunas), with one manual
--    override: the dataset labels Región Metropolitana "XIII" (its
--    position in the roman-numeral creation-order sequence), but Chile
--    always displays it as "RM" in real-world use — confirmed against
--    the mockup itself, which shows "RM" not "XIII".

alter table regions add column admin_region_numeral text;

update regions r set
  admin_region_order = v.admin_region_order,
  admin_region_numeral = v.admin_region_numeral
from (values
  ('Aisén', 15, 'XI'),
  ('Algarrobo', 6, 'V'),
  ('Alhué', 7, 'RM'),
  ('Alto Biobío', 11, 'VIII'),
  ('Alto Hospicio', 2, 'I'),
  ('Alto del Carmen', 4, 'III'),
  ('Ancud', 14, 'X'),
  ('Andacollo', 5, 'IV'),
  ('Angol', 12, 'IX'),
  ('Antofagasta', 3, 'II'),
  ('Antuco', 11, 'VIII'),
  ('Antártica', 16, 'XII'),
  ('Arauco', 11, 'VIII'),
  ('Arica', 1, 'XV'),
  ('Buin', 7, 'RM'),
  ('Bulnes', 10, 'XVI'),
  ('Cabildo', 6, 'V'),
  ('Cabo de Hornos', 16, 'XII'),
  ('Cabrero', 11, 'VIII'),
  ('Calama', 3, 'II'),
  ('Calbuco', 14, 'X'),
  ('Caldera', 4, 'III'),
  ('Calera', 6, 'V'),
  ('Calera de Tango', 7, 'RM'),
  ('Calle Larga', 6, 'V'),
  ('Camarones', 1, 'XV'),
  ('Camiña', 2, 'I'),
  ('Canela', 5, 'IV'),
  ('Carahue', 12, 'IX'),
  ('Cartagena', 6, 'V'),
  ('Casablanca', 6, 'V'),
  ('Castro', 14, 'X'),
  ('Catemu', 6, 'V'),
  ('Cauquenes', 9, 'VII'),
  ('Cañete', 11, 'VIII'),
  ('Cerrillos', 7, 'RM'),
  ('Cerro Navia', 7, 'RM'),
  ('Chaitén', 14, 'X'),
  ('Chanco', 9, 'VII'),
  ('Chañaral', 4, 'III'),
  ('Chiguayante', 11, 'VIII'),
  ('Chile Chico', 15, 'XI'),
  ('Chillán', 10, 'XVI'),
  ('Chillán Viejo', 10, 'XVI'),
  ('Chimbarongo', 8, 'VI'),
  ('Cholchol', 12, 'IX'),
  ('Chonchi', 14, 'X'),
  ('Chépica', 8, 'VI'),
  ('Cisnes', 15, 'XI'),
  ('Cobquecura', 10, 'XVI'),
  ('Cochamó', 14, 'X'),
  ('Cochrane', 15, 'XI'),
  ('Codegua', 8, 'VI'),
  ('Coelemu', 10, 'XVI'),
  ('Coihaique', 15, 'XI'),
  ('Coihueco', 10, 'XVI'),
  ('Coinco', 8, 'VI'),
  ('Colbún', 9, 'VII'),
  ('Colchane', 2, 'I'),
  ('Colina', 7, 'RM'),
  ('Collipulli', 12, 'IX'),
  ('Coltauco', 8, 'VI'),
  ('Combarbalá', 5, 'IV'),
  ('Concepción', 11, 'VIII'),
  ('Conchalí', 7, 'RM'),
  ('Concón', 6, 'V'),
  ('Constitución', 9, 'VII'),
  ('Contulmo', 11, 'VIII'),
  ('Copiapó', 4, 'III'),
  ('Coquimbo', 5, 'IV'),
  ('Coronel', 11, 'VIII'),
  ('Corral', 13, 'XIV'),
  ('Cunco', 12, 'IX'),
  ('Curacautín', 12, 'IX'),
  ('Curacaví', 7, 'RM'),
  ('Curaco de Vélez', 14, 'X'),
  ('Curanilahue', 11, 'VIII'),
  ('Curarrehue', 12, 'IX'),
  ('Curepto', 9, 'VII'),
  ('Curicó', 9, 'VII'),
  ('Dalcahue', 14, 'X'),
  ('Diego de Almagro', 4, 'III'),
  ('Doñihue', 8, 'VI'),
  ('El Bosque', 7, 'RM'),
  ('El Carmen', 10, 'XVI'),
  ('El Monte', 7, 'RM'),
  ('El Quisco', 6, 'V'),
  ('El Tabo', 6, 'V'),
  ('Empedrado', 9, 'VII'),
  ('Ercilla', 12, 'IX'),
  ('Estación Central', 7, 'RM'),
  ('Florida', 11, 'VIII'),
  ('Freire', 12, 'IX'),
  ('Freirina', 4, 'III'),
  ('Fresia', 14, 'X'),
  ('Frutillar', 14, 'X'),
  ('Futaleufú', 14, 'X'),
  ('Futrono', 13, 'XIV'),
  ('Galvarino', 12, 'IX'),
  ('General Lagos', 1, 'XV'),
  ('Gorbea', 12, 'IX'),
  ('Graneros', 8, 'VI'),
  ('Guaitecas', 15, 'XI'),
  ('Hijuelas', 6, 'V'),
  ('Hualaihué', 14, 'X'),
  ('Hualañé', 9, 'VII'),
  ('Hualpén', 11, 'VIII'),
  ('Hualqui', 11, 'VIII'),
  ('Huara', 2, 'I'),
  ('Huasco', 4, 'III'),
  ('Huechuraba', 7, 'RM'),
  ('Illapel', 5, 'IV'),
  ('Independencia', 7, 'RM'),
  ('Iquique', 2, 'I'),
  ('Isla de Maipo', 7, 'RM'),
  ('Isla de Pascua', 6, 'V'),
  ('Juan Fernández', 6, 'V'),
  ('La Cisterna', 7, 'RM'),
  ('La Cruz', 6, 'V'),
  ('La Estrella', 8, 'VI'),
  ('La Florida', 7, 'RM'),
  ('La Granja', 7, 'RM'),
  ('La Higuera', 5, 'IV'),
  ('La Ligua', 6, 'V'),
  ('La Pintana', 7, 'RM'),
  ('La Reina', 7, 'RM'),
  ('La Serena', 5, 'IV'),
  ('La Unión', 13, 'XIV'),
  ('Lago Ranco', 13, 'XIV'),
  ('Lago Verde', 15, 'XI'),
  ('Laguna Blanca', 16, 'XII'),
  ('Laja', 11, 'VIII'),
  ('Lampa', 7, 'RM'),
  ('Lanco', 13, 'XIV'),
  ('Las Cabras', 8, 'VI'),
  ('Las Condes', 7, 'RM'),
  ('Lautaro', 12, 'IX'),
  ('Lebu', 11, 'VIII'),
  ('Licantén', 9, 'VII'),
  ('Limache', 6, 'V'),
  ('Linares', 9, 'VII'),
  ('Litueche', 8, 'VI'),
  ('Llaillay', 6, 'V'),
  ('Llanquihue', 14, 'X'),
  ('Lo Barnechea', 7, 'RM'),
  ('Lo Espejo', 7, 'RM'),
  ('Lo Prado', 7, 'RM'),
  ('Lolol', 8, 'VI'),
  ('Loncoche', 12, 'IX'),
  ('Longaví', 9, 'VII'),
  ('Lonquimay', 12, 'IX'),
  ('Los Andes', 6, 'V'),
  ('Los Lagos', 13, 'XIV'),
  ('Los Muermos', 14, 'X'),
  ('Los Sauces', 12, 'IX'),
  ('Los Vilos', 5, 'IV'),
  ('Los Álamos', 11, 'VIII'),
  ('Los Ángeles', 11, 'VIII'),
  ('Lota', 11, 'VIII'),
  ('Lumaco', 12, 'IX'),
  ('Machalí', 8, 'VI'),
  ('Macul', 7, 'RM'),
  ('Maipú', 7, 'RM'),
  ('Malloa', 8, 'VI'),
  ('Marchihue', 8, 'VI'),
  ('Mariquina', 13, 'XIV'),
  ('María Elena', 3, 'II'),
  ('María Pinto', 7, 'RM'),
  ('Maule', 9, 'VII'),
  ('Maullín', 14, 'X'),
  ('Mejillones', 3, 'II'),
  ('Melipeuco', 12, 'IX'),
  ('Melipilla', 7, 'RM'),
  ('Molina', 9, 'VII'),
  ('Monte Patria', 5, 'IV'),
  ('Mostazal', 8, 'VI'),
  ('Mulchén', 11, 'VIII'),
  ('Máfil', 13, 'XIV'),
  ('Nacimiento', 11, 'VIII'),
  ('Nancagua', 8, 'VI'),
  ('Natales', 16, 'XII'),
  ('Navidad', 8, 'VI'),
  ('Negrete', 11, 'VIII'),
  ('Ninhue', 10, 'XVI'),
  ('Nogales', 6, 'V'),
  ('Nueva Imperial', 12, 'IX'),
  ('O''Higgins', 15, 'XI'),
  ('Olivar', 8, 'VI'),
  ('Ollagüe', 3, 'II'),
  ('Olmué', 6, 'V'),
  ('Osorno', 14, 'X'),
  ('Ovalle', 5, 'IV'),
  ('Padre Hurtado', 7, 'RM'),
  ('Padre las Casas', 12, 'IX'),
  ('Paiguano', 5, 'IV'),
  ('Paillaco', 13, 'XIV'),
  ('Paine', 7, 'RM'),
  ('Palena', 14, 'X'),
  ('Palmilla', 8, 'VI'),
  ('Panguipulli', 13, 'XIV'),
  ('Panquehue', 6, 'V'),
  ('Papudo', 6, 'V'),
  ('Paredones', 8, 'VI'),
  ('Parral', 9, 'VII'),
  ('Pedro Aguirre Cerda', 7, 'RM'),
  ('Pelarco', 9, 'VII'),
  ('Pelluhue', 9, 'VII'),
  ('Pemuco', 10, 'XVI'),
  ('Pencahue', 9, 'VII'),
  ('Penco', 11, 'VIII'),
  ('Peralillo', 8, 'VI'),
  ('Perquenco', 12, 'IX'),
  ('Petorca', 6, 'V'),
  ('Peumo', 8, 'VI'),
  ('Peñaflor', 7, 'RM'),
  ('Peñalolén', 7, 'RM'),
  ('Pica', 2, 'I'),
  ('Pichidegua', 8, 'VI'),
  ('Pichilemu', 8, 'VI'),
  ('Pinto', 10, 'XVI'),
  ('Pirque', 7, 'RM'),
  ('Pitrufquén', 12, 'IX'),
  ('Placilla', 8, 'VI'),
  ('Portezuelo', 10, 'XVI'),
  ('Porvenir', 16, 'XII'),
  ('Pozo Almonte', 2, 'I'),
  ('Primavera', 16, 'XII'),
  ('Providencia', 7, 'RM'),
  ('Puchuncaví', 6, 'V'),
  ('Pucón', 12, 'IX'),
  ('Pudahuel', 7, 'RM'),
  ('Puente Alto', 7, 'RM'),
  ('Puerto Montt', 14, 'X'),
  ('Puerto Octay', 14, 'X'),
  ('Puerto Varas', 14, 'X'),
  ('Pumanque', 8, 'VI'),
  ('Punitaqui', 5, 'IV'),
  ('Punta Arenas', 16, 'XII'),
  ('Puqueldón', 14, 'X'),
  ('Purranque', 14, 'X'),
  ('Purén', 12, 'IX'),
  ('Putaendo', 6, 'V'),
  ('Putre', 1, 'XV'),
  ('Puyehue', 14, 'X'),
  ('Queilén', 14, 'X'),
  ('Quellón', 14, 'X'),
  ('Quemchi', 14, 'X'),
  ('Quilaco', 11, 'VIII'),
  ('Quilicura', 7, 'RM'),
  ('Quilleco', 11, 'VIII'),
  ('Quillota', 6, 'V'),
  ('Quillón', 10, 'XVI'),
  ('Quilpué', 6, 'V'),
  ('Quinchao', 14, 'X'),
  ('Quinta Normal', 7, 'RM'),
  ('Quinta de Tilcoco', 8, 'VI'),
  ('Quintero', 6, 'V'),
  ('Quirihue', 10, 'XVI'),
  ('Rancagua', 8, 'VI'),
  ('Rauco', 9, 'VII'),
  ('Recoleta', 7, 'RM'),
  ('Renaico', 12, 'IX'),
  ('Renca', 7, 'RM'),
  ('Rengo', 8, 'VI'),
  ('Requínoa', 8, 'VI'),
  ('Retiro', 9, 'VII'),
  ('Rinconada', 6, 'V'),
  ('Romeral', 9, 'VII'),
  ('Ránquil', 10, 'XVI'),
  ('Río Bueno', 13, 'XIV'),
  ('Río Claro', 9, 'VII'),
  ('Río Hurtado', 5, 'IV'),
  ('Río Ibáñez', 15, 'XI'),
  ('Río Negro', 14, 'X'),
  ('Río Verde', 16, 'XII'),
  ('Saavedra', 12, 'IX'),
  ('Sagrada Familia', 9, 'VII'),
  ('Salamanca', 5, 'IV'),
  ('San Antonio', 6, 'V'),
  ('San Bernardo', 7, 'RM'),
  ('San Carlos', 10, 'XVI'),
  ('San Clemente', 9, 'VII'),
  ('San Esteban', 6, 'V'),
  ('San Fabián', 10, 'XVI'),
  ('San Felipe', 6, 'V'),
  ('San Fernando', 8, 'VI'),
  ('San Gregorio', 16, 'XII'),
  ('San Ignacio', 10, 'XVI'),
  ('San Javier', 9, 'VII'),
  ('San Joaquín', 7, 'RM'),
  ('San José de Maipo', 7, 'RM'),
  ('San Juan de la Costa', 14, 'X'),
  ('San Miguel', 7, 'RM'),
  ('San Nicolás', 10, 'XVI'),
  ('San Pablo', 14, 'X'),
  ('San Pedro', 7, 'RM'),
  ('San Pedro de Atacama', 3, 'II'),
  ('San Pedro de la Paz', 11, 'VIII'),
  ('San Rafael', 9, 'VII'),
  ('San Ramón', 7, 'RM'),
  ('San Rosendo', 11, 'VIII'),
  ('San Vicente', 8, 'VI'),
  ('Santa Bárbara', 11, 'VIII'),
  ('Santa Cruz', 8, 'VI'),
  ('Santa Juana', 11, 'VIII'),
  ('Santa María', 6, 'V'),
  ('Santiago', 7, 'RM'),
  ('Santo Domingo', 6, 'V'),
  ('Sierra Gorda', 3, 'II'),
  ('Talagante', 7, 'RM'),
  ('Talca', 9, 'VII'),
  ('Talcahuano', 11, 'VIII'),
  ('Taltal', 3, 'II'),
  ('Temuco', 12, 'IX'),
  ('Teno', 9, 'VII'),
  ('Teodoro Schmidt', 12, 'IX'),
  ('Tierra Amarilla', 4, 'III'),
  ('Tiltil', 7, 'RM'),
  ('Timaukel', 16, 'XII'),
  ('Tirúa', 11, 'VIII'),
  ('Tocopilla', 3, 'II'),
  ('Toltén', 12, 'IX'),
  ('Tomé', 11, 'VIII'),
  ('Torres del Paine', 16, 'XII'),
  ('Tortel', 15, 'XI'),
  ('Traiguén', 12, 'IX'),
  ('Treguaco', 10, 'XVI'),
  ('Tucapel', 11, 'VIII'),
  ('Valdivia', 13, 'XIV'),
  ('Vallenar', 4, 'III'),
  ('Valparaíso', 6, 'V'),
  ('Vichuquén', 9, 'VII'),
  ('Victoria', 12, 'IX'),
  ('Vicuña', 5, 'IV'),
  ('Vilcún', 12, 'IX'),
  ('Villa Alegre', 9, 'VII'),
  ('Villa Alemana', 6, 'V'),
  ('Villarrica', 12, 'IX'),
  ('Vitacura', 7, 'RM'),
  ('Viña del Mar', 6, 'V'),
  ('Yerbas Buenas', 9, 'VII'),
  ('Yumbel', 11, 'VIII'),
  ('Yungay', 10, 'XVI'),
  ('Zapallar', 6, 'V'),
  ('Ñiquén', 10, 'XVI'),
  ('Ñuñoa', 7, 'RM')
) as v(name, admin_region_order, admin_region_numeral)
where r.name = v.name;
